### ISSUE TITLE
Why is there no check for an existing user before inviting?

### ISSUE THREAD

**Issue by williscool** [scambra/devise_invitable#273]
It removes all of their attributes 

and could take a whole site down if you make urls based of of names which would no longer be set o.o

Solution? simply:

``` ruby
  def create
    if user_already_there(resource_params[:user])
      set_flash_message(:info, :already_present)
      session[:return_to] ||= request.referer

      redirect_to session[:return_to]
    else
      super
    end
  end

```

``` yml
en:
  devise:
    invitation:
      user:
        already_present: "They've already signed up or been invited."
```
