### ISSUE TITLE
Wrong flash msg upon successfull invitation acceptation and password

### ISSUE THREAD

**Issue by idvix** [scambra/devise_invitable#477]
Gemfile :

```
gem 'devise',           '>= 2.0.0'
gem 'devise_invitable', '~> 1.3.4'
```

Users accessing `/invitation/accept.XX?invitation_token=XXXXXXXX` successfully set their password using this form:

```
<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

  <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>

  <p><%= f.submit t("devise.invitations.edit.submit_button"), class:'btn btn-inverse' %></p>
<% end %>
```

Upon succes, they get signed_in and redirected to the intended page, however they get the flash message located in :

```
en:  
 devise:  
  invitations:  
   invitation_token_invalid: 'The invitation token provided is not valid!'
```

Any idea why so?
