### ISSUE TITLE
Invitation URL is generated incorrectly when the app's locale is not "en"

### ISSUE THREAD

**Issue by robcontreras** [scambra/devise_invitable#538]
this is the content of my "devise_invitable.es.yml"

```
mailer:
      invitation_instructions:
        subject: "Instrucciónes de la Invitación"
        hello: "Hola %{email}"
        someone_invited_you: "Haz sido invitado a %{url}, puedes aceptar la invitación haciendo click sobre el siguiente link:"
        accept: "Aceptar invitación"
```

This is the url that is generated

```
<p>Haz sido invitado a http://localhost:3001/, puedes aceptar la invitaci=
=C3=B3n haciendo click sobre el siguiente link:</p>

<p><a href=3D"http://localhost:3001/users/invitation/accept?invitation_to=
ken=3DDaFUx3SZt-6Hx472wP1R">Aceptar invitaci=C3=B3n</a></p>

```

The issue is in the param name, it makes it **invitation_to=ken**
